### ISSUE TITLE
Create a "Snippets" header for short pieces listed on the issue page

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#126]
As discussed in #86, we'll use small caps for the SNIPPETS header. @gissoo's designs [can be seen here.](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736)

**Comment by thatbudakguy** [comment]
@gissoo this is ready for a look. the designs say "more pieces to read", but i presume we still want "snippets", right? if not i can change it to match the design, just wanted to check.

**Comment by gissoo** [comment]
@thatbudakguy I revised the style of the "Snippets" and proposed two new alternatives since the current style implemented does not at all look like how I imagined (mainly because I had tested it only with the text placeholder "more pieces to read", and also didn't realize how much the real short piece titles would affect the styles of the section title). According to the Slack conversation we just had RSK, Nick, and Grant all agreed to go with a section title "SNIPPETS" in small caps, in Light font weight, with 20% tracking, 18px on mobile and tablet, and 20px on desktop. [Here is the new design](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736)

**Comment by thatbudakguy** [comment]
ok, I've added the new styles to the "snippets" header. i also noticed that the styles for the titles and authors in this section were off (titles should be italic; authors shouldn't) so i fixed that as well. @gissoo lmk if it looks right.

**Comment by gissoo** [comment]
@thatbudakguy thank you for working on this!!! And for catching the missing italics. 

This looks mostly fine, but there are three things I have found:
1. the font size of the "SNIPPETS" on mobile is 0.888889rem which translates to about 14px?? Is this correct? and 1.111 which is about 18px? It should be about 18px on mobile and tablet, and 20px on desktop
2. Following the first point I also went back to test the font size of the essay titles and I noticed the same thing as above – would you please help confirm these? There is a chance these are smaller than the design – I didn't think they did before.
3. the snippet titles are not changing between desktop and mobile – they are always at 0.88889rem which is about 14px?? They should be 14px on mobile and tablet and 16px on desktop.

**Comment by thatbudakguy** [comment]
1. it's 1rem for me; not sure where you're getting this number? can you post a screenshot?
<img width="546" alt="Screen Shot 2020-10-14 at 1 53 29 PM" src="https://user-images.githubusercontent.com/4924494/96026600-b7c9cf80-0e24-11eb-9b11-87adb246d8f2.png">

2. same as above
3. edited to set them to 16px for desktop.

**Comment by gissoo** [comment]
1. This is what I see – It's still showing me as 1.111rem, 1 or 1.111, are both still smaller than 20px. 
![Screen Shot 2020-10-14 at 2.44.17 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/bad185ba-8f5b-4f9a-bc96-319c9c31011b)


2. not showing me the header itself, but "article summary" as 1.1111rem
![Screen Shot 2020-10-14 at 2.47.47 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/18726c9b-094d-4b3d-8d21-dfc016bd0279)

**Comment by thatbudakguy** [comment]
1.11111rem x 18px = 20px. our base font size (1rem) is 18px.

**Comment by thatbudakguy** [comment]
check the "computed" tab on the far right to see what size it's actually rendering as.

**Comment by gissoo** [comment]
OMG! @thatbudakguy thank you!!!
